//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartHidden {
            get {
                return ((bool)(this["StartHidden"]));
            }
            set {
                this["StartHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartToolbar {
            get {
                return ((bool)(this["StartToolbar"]));
            }
            set {
                this["StartToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RegisterHotkeys {
            get {
                return ((bool)(this["RegisterHotkeys"]));
            }
            set {
                this["RegisterHotkeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public string hkUpperCaseKey {
            get {
                return ((string)(this["hkUpperCaseKey"]));
            }
            set {
                this["hkUpperCaseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string hkLowerCaseKey {
            get {
                return ((string)(this["hkLowerCaseKey"]));
            }
            set {
                this["hkLowerCaseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string hkPlainTextKey {
            get {
                return ((string)(this["hkPlainTextKey"]));
            }
            set {
                this["hkPlainTextKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Back")]
        public string hkCapsLockKey {
            get {
                return ((string)(this["hkCapsLockKey"]));
            }
            set {
                this["hkCapsLockKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string hkProcessTextKey {
            get {
                return ((string)(this["hkProcessTextKey"]));
            }
            set {
                this["hkProcessTextKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveMemorySlots {
            get {
                return ((bool)(this["SaveMemorySlots"]));
            }
            set {
                this["SaveMemorySlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemorySlotFolder {
            get {
                return ((string)(this["MemorySlotFolder"]));
            }
            set {
                this["MemorySlotFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResetCounterWhenSet {
            get {
                return ((bool)(this["ResetCounterWhenSet"]));
            }
            set {
                this["ResetCounterWhenSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendCut {
            get {
                return ((bool)(this["sendCut"]));
            }
            set {
                this["sendCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendType {
            get {
                return ((bool)(this["sendType"]));
            }
            set {
                this["sendType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendPaste {
            get {
                return ((bool)(this["sendPaste"]));
            }
            set {
                this["sendPaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkUpperCaseCtrl {
            get {
                return ((bool)(this["hkUpperCaseCtrl"]));
            }
            set {
                this["hkUpperCaseCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkUpperCaseAlt {
            get {
                return ((bool)(this["hkUpperCaseAlt"]));
            }
            set {
                this["hkUpperCaseAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkUpperCaseShift {
            get {
                return ((bool)(this["hkUpperCaseShift"]));
            }
            set {
                this["hkUpperCaseShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkUpperCaseWin {
            get {
                return ((bool)(this["hkUpperCaseWin"]));
            }
            set {
                this["hkUpperCaseWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkLowerCaseCtrl {
            get {
                return ((bool)(this["hkLowerCaseCtrl"]));
            }
            set {
                this["hkLowerCaseCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkLowerCaseAlt {
            get {
                return ((bool)(this["hkLowerCaseAlt"]));
            }
            set {
                this["hkLowerCaseAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkLowerCaseShift {
            get {
                return ((bool)(this["hkLowerCaseShift"]));
            }
            set {
                this["hkLowerCaseShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkLowerCaseWin {
            get {
                return ((bool)(this["hkLowerCaseWin"]));
            }
            set {
                this["hkLowerCaseWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkPlainTextCtrl {
            get {
                return ((bool)(this["hkPlainTextCtrl"]));
            }
            set {
                this["hkPlainTextCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkPlainTextAlt {
            get {
                return ((bool)(this["hkPlainTextAlt"]));
            }
            set {
                this["hkPlainTextAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkPlainTextShift {
            get {
                return ((bool)(this["hkPlainTextShift"]));
            }
            set {
                this["hkPlainTextShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkPlainTextWin {
            get {
                return ((bool)(this["hkPlainTextWin"]));
            }
            set {
                this["hkPlainTextWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkProcessTextCtrl {
            get {
                return ((bool)(this["hkProcessTextCtrl"]));
            }
            set {
                this["hkProcessTextCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkProcessTextAlt {
            get {
                return ((bool)(this["hkProcessTextAlt"]));
            }
            set {
                this["hkProcessTextAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkProcessTextShift {
            get {
                return ((bool)(this["hkProcessTextShift"]));
            }
            set {
                this["hkProcessTextShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkProcessTextWin {
            get {
                return ((bool)(this["hkProcessTextWin"]));
            }
            set {
                this["hkProcessTextWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkCapsLockCtrl {
            get {
                return ((bool)(this["hkCapsLockCtrl"]));
            }
            set {
                this["hkCapsLockCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCapsLockAlt {
            get {
                return ((bool)(this["hkCapsLockAlt"]));
            }
            set {
                this["hkCapsLockAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkCapsLockShift {
            get {
                return ((bool)(this["hkCapsLockShift"]));
            }
            set {
                this["hkCapsLockShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCapsLockWin {
            get {
                return ((bool)(this["hkCapsLockWin"]));
            }
            set {
                this["hkCapsLockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool updateClipboard {
            get {
                return ((bool)(this["updateClipboard"]));
            }
            set {
                this["updateClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string hkDateKey {
            get {
                return ((string)(this["hkDateKey"]));
            }
            set {
                this["hkDateKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkDateCtrl {
            get {
                return ((bool)(this["hkDateCtrl"]));
            }
            set {
                this["hkDateCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkDateAlt {
            get {
                return ((bool)(this["hkDateAlt"]));
            }
            set {
                this["hkDateAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkDateShift {
            get {
                return ((bool)(this["hkDateShift"]));
            }
            set {
                this["hkDateShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkDateWin {
            get {
                return ((bool)(this["hkDateWin"]));
            }
            set {
                this["hkDateWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string hkMemSlot1Key {
            get {
                return ((string)(this["hkMemSlot1Key"]));
            }
            set {
                this["hkMemSlot1Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot1Ctrl {
            get {
                return ((bool)(this["hkMemSlot1Ctrl"]));
            }
            set {
                this["hkMemSlot1Ctrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot1Alt {
            get {
                return ((bool)(this["hkMemSlot1Alt"]));
            }
            set {
                this["hkMemSlot1Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot1Shift {
            get {
                return ((bool)(this["hkMemSlot1Shift"]));
            }
            set {
                this["hkMemSlot1Shift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot1Win {
            get {
                return ((bool)(this["hkMemSlot1Win"]));
            }
            set {
                this["hkMemSlot1Win"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string hkMemSlot2Key {
            get {
                return ((string)(this["hkMemSlot2Key"]));
            }
            set {
                this["hkMemSlot2Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot2Ctrl {
            get {
                return ((bool)(this["hkMemSlot2Ctrl"]));
            }
            set {
                this["hkMemSlot2Ctrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot2Alt {
            get {
                return ((bool)(this["hkMemSlot2Alt"]));
            }
            set {
                this["hkMemSlot2Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot2Shift {
            get {
                return ((bool)(this["hkMemSlot2Shift"]));
            }
            set {
                this["hkMemSlot2Shift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot2Win {
            get {
                return ((bool)(this["hkMemSlot2Win"]));
            }
            set {
                this["hkMemSlot2Win"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string hkMemSlot3Key {
            get {
                return ((string)(this["hkMemSlot3Key"]));
            }
            set {
                this["hkMemSlot3Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot3Ctrl {
            get {
                return ((bool)(this["hkMemSlot3Ctrl"]));
            }
            set {
                this["hkMemSlot3Ctrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot3Alt {
            get {
                return ((bool)(this["hkMemSlot3Alt"]));
            }
            set {
                this["hkMemSlot3Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkMemSlot3Shift {
            get {
                return ((bool)(this["hkMemSlot3Shift"]));
            }
            set {
                this["hkMemSlot3Shift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkMemSlot3Win {
            get {
                return ((bool)(this["hkMemSlot3Win"]));
            }
            set {
                this["hkMemSlot3Win"] = value;
            }
        }
    }
}
